server {
  listen 80;
  server_name optoelectronica.agustingimenez.ar;
  root /var/www/optoelectronica;
  index index.html index.php;

  location / {
    try_files $uri $uri/ =404;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/var/run/php/php-fpm.sock; # ajustar según sistema
  }

  access_log /var/log/nginx/optoelectronica.access.log;
  error_log /var/log/nginx/optoelectronica.error.log;
}
